# Generated by Django 4.0.5 on 2022-06-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_modelnews_options_modelnews_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelnews',
            name='image',
        ),
    ]
