# Generated by Django 4.0.5 on 2022-06-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_modelсategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelсategory',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='modelсategory',
            name='deleted',
            field=models.BooleanField(default=True),
        ),
    ]
