# Generated by Django 4.0.5 on 2022-06-26 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_modelaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelaction',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AlterField(
            model_name='modelсategory',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.CreateModel(
            name='modelProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagesProduct', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('сharacteristics', models.TextField(blank=True, verbose_name='Характеристики')),
                ('price', models.DecimalField(decimal_places=10, max_digits=16, verbose_name='Цена')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.modelaction')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.modelсategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
